name: Deploy to Hostinger

on:
  repository_dispatch:
    types:
      - blog-update

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the build branch
        uses: actions/checkout@v3
        with:
          ref: build  # Specify the build branch here

      - name: Upload to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.goodview-moving.com
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /public_html/
