name: Deploy Nuxt 3 Static Site

on:
  push:
    branches:
      - master # Remove this line if your primary branch is "main"
  repository_dispatch:
    types:
      - blog-update
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
  #     - name: git-checkout
  #       uses: actions/checkout@v2
        
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #           node-version: 20
      
  #     - name: Remove node_module
  #       run: rm -rf node_modules
      
  #     - name: Install yarn
  #       run: npm install yarn -g
        
  #     - name: Install all dependencies
  #       run: yarn

  #     - name: Build
  #       run: yarn generate # The build command of your project

  #     - name: Add trailing slashes to sitemap links
  #       run: |
  #         sed -i 's#<loc>\(.*[^/]\)</loc>#<loc>\1/</loc>#g' ./dist/sitemap.xml
    
  #     - name: Push
  #       uses: s0/git-publish-subdir-action@develop
  #       env:
  #         REPO: self
  #         BRANCH: build # The branch name where you want to push the assets
  #         FOLDER: dist
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
  #         MESSAGE: "Build: ({sha}) {msg}" # The commit message

      - name: Upload to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 88.223.84.194
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /public_html/
